import 'package:flutter/material.dart';
import '../services/api_service.dart';
import '../widgets/dashboard_scaffold.dart';
import 'online_class_list_screen.dart';

class _Base extends StatelessWidget {
  final String title; final Widget child;
  const _Base({required this.title, required this.child});
  @override Widget build(BuildContext c) => Scaffold(appBar: AppBar(title: Text(title)), body: child);
}

class ClassesScreen extends StatefulWidget { const ClassesScreen({super.key}); @override State<ClassesScreen> createState()=>_ClassesScreenState(); }
class _ClassesScreenState extends State<ClassesScreen> { List _items=[]; bool loading=true;
  Future<void> load() async { final r=await ApiService.get('manager/list-classes'); if(mounted)setState(()=>{_items=r['success']==true?r['data']:[], loading=false}); }
  @override void initState(){super.initState();load();}
  Future<void> add() async { final n=TextEditingController(), g=TextEditingController(); final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:const Text('افزودن کلاس'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:n,decoration:const InputDecoration(labelText:'نام کلاس')),TextField(controller:g,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'پایه'))]),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('لغو')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('ثبت'))])); if(ok==true){final r=await ApiService.post('manager/add-class',{'name':n.text.trim(),'grade_level':int.tryParse(g.text)??1},auth:true); if(mounted){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(r['message']??(r['success']==true?'ثبت شد':'خطا'))));} if(r['success']==true)load();}}
  @override Widget build(BuildContext c)=>_Base(title:'کلاس‌ها',child:loading?const Center(child:CircularProgressIndicator()):Column(children:[Padding(padding:const EdgeInsets.all(12),child:Align(alignment:Alignment.centerLeft,child:FilledButton.icon(onPressed:add,icon:const Icon(Icons.add),label:const Text('کلاس جدید')))),Expanded(child:ListView.builder(itemCount:_items.length,itemBuilder:(_,i){final x=_items[i];return Card(child:ListTile(title:Text(x['name']),subtitle:Text('پایه ${x['grade_level']}  •  کد ${x['class_code']}'),leading:const Icon(Icons.meeting_room));})))]));
}

class PeopleScreen extends StatefulWidget { final bool teachers; const PeopleScreen({super.key,required this.teachers}); @override State<PeopleScreen> createState()=>_PeopleScreenState(); }
class _PeopleScreenState extends State<PeopleScreen>{List _items=[];List _classes=[];bool loading=true;
 Future<void> load()async{final r=await ApiService.get(widget.teachers?'manager/list-teachers':'manager/list-students');final c=await ApiService.get('manager/list-classes');if(mounted)setState(()=>{_items=r['success']==true?r['data']:[],_classes=c['success']==true?c['data']:[],loading=false});}
 @override void initState(){super.initState();load();}
 Future<void> add()async{final name=TextEditingController(),u=TextEditingController(),p=TextEditingController();int? cid;final ok=await showDialog<bool>(context:context,builder:(_)=>StatefulBuilder(builder:(c,s)=>AlertDialog(title:Text(widget.teachers?'افزودن معلم':'افزودن دانش‌آموز'),content:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:name,decoration:const InputDecoration(labelText:'نام و نام خانوادگی')),TextField(controller:u,decoration:const InputDecoration(labelText:'نام کاربری')),TextField(controller:p,obscureText:true,decoration:const InputDecoration(labelText:'رمز عبور')),if(!widget.teachers)DropdownButtonFormField<int>(value:cid,items:_classes.map<DropdownMenuItem<int>>((x)=>DropdownMenuItem(value:x['id'],child:Text(x['name']))).toList(),onChanged:(v)=>s(()=>cid=v),decoration:const InputDecoration(labelText:'کلاس'))])),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('لغو')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('ثبت'))])));if(ok==true){final body={'full_name':name.text.trim(),'username':u.text.trim(),'password':p.text.trim(),if(!widget.teachers)'class_id':cid};final r=await ApiService.post(widget.teachers?'manager/add-teacher':'manager/add-student',body,auth:true);if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(r['message']??(r['success']==true?'ثبت شد':'خطا'))));if(r['success']==true)load();}}
 @override Widget build(BuildContext c)=>_Base(title:widget.teachers?'معلم‌ها':'دانش‌آموزان',child:loading?const Center(child:CircularProgressIndicator()):Column(children:[Padding(padding:const EdgeInsets.all(12),child:Align(alignment:Alignment.centerLeft,child:FilledButton.icon(onPressed:add,icon:const Icon(Icons.person_add),label:const Text('افزودن')))),Expanded(child:ListView.builder(itemCount:_items.length,itemBuilder:(_,i){final x=_items[i];return Card(child:ListTile(title:Text(x['full_name']??''),subtitle:Text('${x['username']??''}${x['class_name']!=null?' • ${x['class_name']}':''}'),leading:Icon(widget.teachers?Icons.person:Icons.school)));}))]));
}

class AnnouncementsScreen extends StatefulWidget { final bool student; const AnnouncementsScreen({super.key,this.student=false}); @override State<AnnouncementsScreen> createState()=>_AnnouncementsScreenState(); }
class _AnnouncementsScreenState extends State<AnnouncementsScreen>{List _items=[];bool loading=true;Future<void>load()async{final r=await ApiService.get(widget.student?'student/list-announcements':'manager/list-announcements');if(mounted)setState(()=>{_items=r['success']==true?r['data']:[],loading=false});} @override void initState(){super.initState();load();}
 Future<void> add()async{final t=TextEditingController(),b=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:const Text('اطلاعیه جدید'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:t,decoration:const InputDecoration(labelText:'عنوان')),TextField(controller:b,maxLines:4,decoration:const InputDecoration(labelText:'متن'))]),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('لغو')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('ارسال'))]));if(ok==true){final r=await ApiService.post('manager/add-announcement',{'title':t.text.trim(),'content':b.text.trim()},auth:true);if(r['success']==true)load();}}
 @override Widget build(BuildContext c)=>_Base(title:'اطلاعیه‌ها',child:loading?const Center(child:CircularProgressIndicator()):Column(children:[if(!widget.student)Padding(padding:const EdgeInsets.all(12),child:Align(alignment:Alignment.centerLeft,child:FilledButton.icon(onPressed:add,icon:const Icon(Icons.add),label:const Text('اطلاعیه جدید')))),Expanded(child:ListView.builder(itemCount:_items.length,itemBuilder:(_,i){final x=_items[i];return Card(child:ListTile(title:Text(x['title']??''),subtitle:Text(x['content']??''),isThreeLine:true));}))]));}

class TeacherClassesScreen extends StatefulWidget{const TeacherClassesScreen({super.key});@override State<TeacherClassesScreen>createState()=>_TeacherClassesScreenState();}
class _TeacherClassesScreenState extends State<TeacherClassesScreen>{List _items=[];bool loading=true;@override void initState(){super.initState();load();}Future<void>load()async{final r=await ApiService.get('teacher/list-classes');if(mounted)setState(()=>{_items=r['success']==true?r['data']:[],loading=false});}@override Widget build(BuildContext c)=>_Base(title:'کلاس‌های من',child:loading?const Center(child:CircularProgressIndicator()):ListView.builder(padding:const EdgeInsets.all(12),itemCount:_items.length,itemBuilder:(_,i){final x=_items[i];return Card(child:ListTile(title:Text(x['name']),subtitle:Text('پایه ${x['grade_level']} • کد ${x['class_code']}'),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>TeacherClassDetail(classId:x['id'],name:x['name']))));}));}}
class TeacherClassDetail extends StatefulWidget{final dynamic classId;final String name;const TeacherClassDetail({super.key,required this.classId,required this.name});@override State<TeacherClassDetail>createState()=>_TeacherClassDetailState();}
class _TeacherClassDetailState extends State<TeacherClassDetail>{List _students=[];List _assign=[];bool loading=true;@override void initState(){super.initState();load();}Future<void>load()async{final a=await ApiService.get('teacher/list-students?class_id=${widget.classId}');final b=await ApiService.get('teacher/list-assignments?class_id=${widget.classId}');if(mounted)setState(()=>{_students=a['success']==true?a['data']:[],_assign=b['success']==true?b['data']:[],loading=false});}@override Widget build(BuildContext c)=>_Base(title:widget.name,child:loading?const Center(child:CircularProgressIndicator()):ListView(padding:const EdgeInsets.all(12),children:[const Text('دانش‌آموزان',style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)),..._students.map((x)=>ListTile(leading:const Icon(Icons.person),title:Text(x['full_name']??''),subtitle:Text(x['username']??''))),const Divider(),const Text('تکالیف',style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)),..._assign.map((x)=>ListTile(leading:const Icon(Icons.assignment),title:Text(x['title']??''),subtitle:Text('کد ${x['assignment_code']??''} • ${x['submitted']??''}')))]));}

class AssignmentScreen extends StatefulWidget{const AssignmentScreen({super.key});@override State<AssignmentScreen>createState()=>_AssignmentScreenState();}
class _AssignmentScreenState extends State<AssignmentScreen>{List _items=[];bool loading=true;@override void initState(){super.initState();load();}Future<void>load()async{final r=await ApiService.get('student/list-assignments');if(mounted)setState(()=>{_items=r['success']==true?r['data']:[],loading=false});} @override Widget build(BuildContext c)=>_Base(title:'تکالیف',child:loading?const Center(child:CircularProgressIndicator()):ListView.builder(padding:const EdgeInsets.all(12),itemCount:_items.length,itemBuilder:(_,i){final x=_items[i];return Card(child:ListTile(title:Text(x['title']??''),subtitle:Text('${x['teacher_name']??''} • ${x['submitted']==1?'تحویل شده':'تحویل نشده'}'),onTap:()=>showDialog(context:c,builder:(_)=>AlertDialog(title:Text(x['title']??''),content:Text(x['description']??'توضیحی ثبت نشده'),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('بستن'))]))));}));}

class MyTeachersScreen extends StatefulWidget{const MyTeachersScreen({super.key});@override State<MyTeachersScreen>createState()=>_MyTeachersScreenState();}class _MyTeachersScreenState extends State<MyTeachersScreen>{List _items=[];@override void initState(){super.initState();load();}Future<void>load()async{final r=await ApiService.get('student/list-teachers');if(mounted)setState(()=>_items=r['success']==true?r['data']:[]);}@override Widget build(BuildContext c)=>_Base(title:'معلم‌های من',child:ListView.builder(itemCount:_items.length,itemBuilder:(_,i)=>ListTile(leading:const Icon(Icons.person),title:Text(_items[i]['full_name']??''))));}

class AdminSettingsScreen extends StatefulWidget{final String schoolId;final String schoolName;const AdminSettingsScreen({super.key,required this.schoolId,required this.schoolName});@override State<AdminSettingsScreen>createState()=>_AdminSettingsScreenState();}
class _AdminSettingsScreenState extends State<AdminSettingsScreen>{Map<String,bool> f={};final limit=TextEditingController();String p='#2F5FFF',s='#FFB020';@override void initState(){super.initState();load();}Future<void>load()async{final r=await ApiService.get('admin/list-school-features?school_id=${widget.schoolId}');if(r['success']==true&&r['data'] is List){for(final x in r['data'])f[x['feature_key']]=(x['enabled']==1||x['enabled']==true);}final schools=await ApiService.get('admin/list-schools');if(schools['success']==true){for(final x in schools['data'])if('${x['id']}'==widget.schoolId){limit.text='${x['free_message_limit']??1}';p=x['theme_primary_color']??p;s=x['theme_secondary_color']??s;}}if(mounted)setState((){});}Future<void>saveFeature(String k,bool v)async{final r=await ApiService.post('admin/set-school-feature',{'school_id':int.tryParse(widget.schoolId)??widget.schoolId,'feature_key':k,'enabled':v},auth:true);if(r['success']!=true&&mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(r['message']??'خطا')));}Future<void>saveLimit()async{final r=await ApiService.post('admin/set-school-settings',{'school_id':int.tryParse(widget.schoolId)??widget.schoolId,'free_message_limit':int.tryParse(limit.text)??1},auth:true);if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(r['message']??(r['success']==true?'ذخیره شد':'خطا'))));}
@override Widget build(BuildContext c)=>_Base(title:'تنظیمات ${widget.schoolName}',child:ListView(padding:const EdgeInsets.all(16),children:[const Text('قابلیت‌ها',style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)),...['exams','late_penalty','resubmit','points','online_class'].map((k)=>SwitchListTile(title:Text(k),value:f[k]??true,onChanged:(v){setState(()=>f[k]=v);saveFeature(k,v);})),TextField(controller:limit,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'تعداد پیام آزاد دانش‌آموز')),const SizedBox(height:12),FilledButton(onPressed:saveLimit,child:const Text('ذخیره تنظیمات پیام'))]));}

class AddAssignmentScreen extends StatefulWidget{const AddAssignmentScreen({super.key});@override State<AddAssignmentScreen>createState()=>_AddAssignmentScreenState();}
class _AddAssignmentScreenState extends State<AddAssignmentScreen>{List _classes=[];int? cid;final title=TextEditingController(),desc=TextEditingController(),score=TextEditingController(text:'20');bool loading=true,saving=false;@override void initState(){super.initState();load();}Future<void>load()async{final r=await ApiService.get('teacher/list-classes');if(mounted)setState(()=>{_classes=r['success']==true?r['data']:[],loading=false});}Future<void>save()async{if(cid==null||title.text.trim().isEmpty)return;setState(()=>saving=true);final r=await ApiService.uploadMultipart('teacher/add-assignment',{'class_id':'$cid','title':title.text.trim(),'description':desc.text.trim(),'type':'text','max_score':score.text.trim()});if(mounted){setState(()=>saving=false);ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(r['message']??(r['success']==true?'تکلیف ثبت شد':'خطا'))));if(r['success']==true)Navigator.pop(context,true);}}@override Widget build(BuildContext c)=>_Base(title:'افزودن تکلیف',child:loading?const Center(child:CircularProgressIndicator()):ListView(padding:const EdgeInsets.all(16),children:[DropdownButtonFormField<int>(value:cid,items:_classes.map<DropdownMenuItem<int>>((x)=>DropdownMenuItem(value:x['id'],child:Text(x['name']))).toList(),onChanged:(v)=>setState(()=>cid=v),decoration:const InputDecoration(labelText:'کلاس')),TextField(controller:title,decoration:const InputDecoration(labelText:'عنوان تکلیف')),TextField(controller:desc,maxLines:5,decoration:const InputDecoration(labelText:'توضیحات')),TextField(controller:score,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'نمره کل')),const SizedBox(height:18),FilledButton(onPressed:saving?null:save,child:Text(saving?'در حال ثبت...':'ثبت تکلیف'))]));}

class MessagesScreen extends StatefulWidget{const MessagesScreen({super.key});@override State<MessagesScreen>createState()=>_MessagesScreenState();}
class _MessagesScreenState extends State<MessagesScreen>{List _items=[];bool loading=true;@override void initState(){super.initState();load();}Future<void>load()async{final r=await ApiService.get('messages/list-threads');if(mounted)setState(()=>{_items=r['success']==true?r['data']:[],loading=false});}Future<void>openThread(dynamic x)async{final id=x['id'];final r=await ApiService.get('messages/list?thread_id=$id');if(!mounted)return;final messages=r['success']==true?(r['data']??[]):[];showDialog(context:context,builder:(d)=>AlertDialog(title:Text('گفتگو با ${x['student_name']??x['teacher_name']??''}'),content:SizedBox(width:400,height:350,child:ListView(children:messages.map<Widget>((m)=>ListTile(title:Text(m['sender_role']=='teacher'?'معلم':'دانش‌آموز'),subtitle:Text(m['content']??''))).toList())),actions:[if(x['status']!='allowed')TextButton(onPressed:()async{final rr=await ApiService.post('messages/allow-continue',{'thread_id':id},auth:true);if(d.mounted)Navigator.pop(d);if(rr['success']==true)load();},child:const Text('اجازه ادامه')) ,TextButton(onPressed:()=>Navigator.pop(d),child:const Text('بستن'))]));}
@override Widget build(BuildContext c)=>_Base(title:'پیام‌ها',child:loading?const Center(child:CircularProgressIndicator()):ListView.builder(itemCount:_items.length,itemBuilder:(_,i){final x=_items[i];return Card(child:ListTile(title:Text(x['student_name']??x['teacher_name']??'گفتگو'),subtitle:Text('وضعیت: ${x['status']}'),onTap:()=>openThread(x)));}));}
